title: {{page.title}}
description: {{page.description}}







baseurl: /personal-blog
exclude: ['README.md']
title: page.title


sass:
    load_paths:
        - _sass
        - node_modules

gems:
  - jekyll-seo-tag
