title: {{page.title}}
description: {{page.meta}}
url: https://danieldeicide.github.io/personal-blog/
author: Daniel Deicide
twitter:
  username: danieldeicide
logo:







baseurl: /personal-blog
exclude: ['README.md']
title: page.title


sass:
    load_paths:
        - _sass
        - node_modules

gems:
  - jekyll-seo-tag
  - octopress-minify-html
